version: '3.9'

x-logging: &default-logging
  options:
    max-size: "40m"
    max-file: "10"
  driver: json-file

services:
  blackarch:
    container_name: blackarch
    build:
      context: .
      dockerfile: Dockerfile.blackarch
