AUTHOR='@xer0dayz'
VULN_NAME='Cisco VPN Login Detected'
URI='/+CSCOE+/logon.html'
METHOD='GET'
MATCH="CSCO_Format"
SEVERITY='P5 - INFO'
CURL_OPTS="--user-agent '' -s -L --insecure"
SECONDARY_COMMANDS=''
GREP_OPTIONS='-i'