AUTHOR='@xer0dayz'
VULN_NAME='Cisco VPN Detected'
URI='/+CSCOE+/win.js'
METHOD='GET'
MATCH="CSCO_WebVPN"
SEVERITY='P5 - INFO'
CURL_OPTS="--user-agent '' -s -L --insecure"
SECONDARY_COMMANDS=''
GREP_OPTIONS='-i'