AUTHOR='@xer0dayz'
VULN_NAME='Citrix VPN Detected 2'
URI='/vpn/index.html'
METHOD='GET'
MATCH="NetScaler "
SEVERITY='P5 - INFO'
CURL_OPTS="--user-agent '' -s -L --insecure"
SECONDARY_COMMANDS=''
GREP_OPTIONS='-i'