AUTHOR='@xer0dayz'
VULN_NAME='Citrix VPN Detected'
URI='/vpn/index.html'
METHOD='GET'
MATCH='Gateway'
SEVERITY='P5 - INFO'
CURL_OPTS="--user-agent '' -s -L --insecure"
SECONDARY_COMMANDS=''
GREP_OPTIONS='-i'