AUTHOR='@xer0dayz'
VULN_NAME='Atlassian Confluence Detected'
URI='/'
METHOD='GET'
MATCH="Atlassian\ Confluence"
SEVERITY='P5 - INFO'
CURL_OPTS="--user-agent '' -s -L --insecure"
SECONDARY_COMMANDS=''
GREP_OPTIONS='-i'