AUTHOR='@xer0dayz'
VULN_NAME='Drupal Detected 3'
URI='/drupal/'
METHOD='GET'
MATCH="drupal\.org"
SEVERITY='P5 - INFO'
CURL_OPTS="--user-agent '' -s -L --insecure"
SECONDARY_COMMANDS=''
GREP_OPTIONS='-i'