AUTHOR='@xer0dayz'
VULN_NAME='F5 BIG-IP Detected 2'
URI='/tmui/login.jsp'
METHOD='GET'
MATCH='<title>F5 BIG-IP'
SEVERITY='P5 - INFO'
CURL_OPTS="--user-agent '' -s -L --insecure"
SECONDARY_COMMANDS=''
GREP_OPTIONS='-i'