AUTHOR='@xer0dayz'
VULN_NAME='Jira Detected 1'
URI='/secure/Dashboard.jspa'
METHOD='GET'
MATCH='Project Management Software'
SEVERITY='P5 - INFO'
CURL_OPTS="--user-agent '' -s -L --insecure"
SECONDARY_COMMANDS=''
GREP_OPTIONS='-i'