AUTHOR='@xer0dayz'
VULN_NAME='Jira Detected'
URI='/secure/ContactAdministrators!default.jspa'
METHOD='GET'
MATCH='Project Management Software'
SEVERITY='P5 - INFO'
CURL_OPTS="--user-agent '' -s -L --insecure"
SECONDARY_COMMANDS=''
GREP_OPTIONS='-i'