AUTHOR='@xer0dayz'
VULN_NAME='MobileIron Login 3'
URI='/mifs/c/d/android.html'
METHOD='GET'
MATCH="MobileIron"
SEVERITY='P5 - INFO'
CURL_OPTS="--user-agent '' -s -L --insecure"
SECONDARY_COMMANDS=''
GREP_OPTIONS='-i'