AUTHOR='@xer0dayz'
VULN_NAME='MobileIron Login 2'
URI='/mifs/login.jsp'
METHOD='GET'
MATCH="MobileIron"
SEVERITY='P5 - INFO'
CURL_OPTS="--user-agent '' -s -L --insecure"
SECONDARY_COMMANDS=''
GREP_OPTIONS='-i'