AUTHOR='@xer0dayz'
VULN_NAME='MS SQL Reporting Server Detected 1'
URI='/ReportServer/pages/ReportViewer.aspx'
METHOD='GET'
MATCH='Microsoft\.Reporting'
SEVERITY='P5 - INFO'
CURL_OPTS="--user-agent '' -s -L --insecure"
SECONDARY_COMMANDS=''
GREP_OPTIONS='-i'