AUTHOR='@xer0dayz'
VULN_NAME='Sitemap.xml Detected'
URI='/sitemap.xml'
METHOD='GET'
MATCH='<?xml\ '
SEVERITY='P5 - INFO'
CURL_OPTS="--user-agent '' -s -L --insecure"
SECONDARY_COMMANDS=''
GREP_OPTIONS='-i'