AUTHOR='@xer0dayz'
VULN_NAME='SolarWinds Orion Panel'
URI='/Orion/Login.aspx'
METHOD='GET'
MATCH="SolarWinds\ Orion"
SEVERITY='P5 - INFO'
CURL_OPTS="--user-agent '' -s -L --insecure"
SECONDARY_COMMANDS=''
GREP_OPTIONS='-i'