AUTHOR='@xer0dayz'
VULN_NAME='SQLiteManager Detected'
URI='/sqlite/'
METHOD='GET'
MATCH='<title>SQLiteManager'
SEVERITY='P5 - INFO'
CURL_OPTS="--user-agent '' -s -L --insecure"
SECONDARY_COMMANDS=''
GREP_OPTIONS='-i'