AUTHOR='@xer0dayz'
VULN_NAME='TeamQuest Login Found'
URI='/teamquest/cgi-bin/login'
METHOD='GET'
MATCH="TeamQuest\ \-\ Login"
SEVERITY='P5 - INFO'
CURL_OPTS="--user-agent '' -s -L --insecure"
SECONDARY_COMMANDS=''
GREP_OPTIONS='-i'