AUTHOR='@xer0dayz'
VULN_NAME='Tiki Wiki CMS Groupware'
URI='/tiki-login.php'
METHOD='GET'
MATCH="Groupware"
SEVERITY='P5 - INFO'
CURL_OPTS="--user-agent '' -s -L --insecure"
SECONDARY_COMMANDS=''
GREP_OPTIONS='-i'