AUTHOR='@xer0dayz'
VULN_NAME='Unauthenticated Jenkins Dashboard Detected'
URI='/'
METHOD='GET'
MATCH="\[Jenkins\]"
SEVERITY='P2 - HIGH'
CURL_OPTS="--user-agent '' -s -L --insecure"
SECONDARY_COMMANDS=''
GREP_OPTIONS='-i'