AUTHOR='@xer0dayz'
VULN_NAME='Web Config Detected 1'
URI='/web.config'
METHOD='GET'
MATCH='<configuration>'
SEVERITY='P4 - LOW'
CURL_OPTS="-L --user-agent '' -s --insecure"
SECONDARY_COMMANDS=''
GREP_OPTIONS='-i'