AUTHOR='@xer0dayz'
VULN_NAME='Wordpress WP-File-Manager Version Detected'
URI="/wp-content/plugins/wp-file-manager/readme.txt"
METHOD='GET'
MATCH="Stable\ tag\:"
SEVERITY='P5 - INFO'
CURL_OPTS="--user-agent '' -s -L --insecure"
SECONDARY_COMMANDS=''
GREP_OPTIONS='-i'