AUTHOR='@xer0dayz'
VULN_NAME='Default Credentials - BruteX'
FILENAME="$LOOT_DIR/credentials/brutex-$TARGET.txt $LOOT_DIR/credentials/brutex-$TARGET-*.txt"
MATCH="password\:\ "
SEVERITY='P1 - CRITICAL'
GREP_OPTIONS='-i'
SEARCH='positive'
SECONDARY_COMMANDS=''
TYPE="network"