AUTHOR='@xer0dayz'
VULN_NAME='Interesting Domain Found'
FILENAME="$LOOT_DIR/domains/domains-all-sorted_NA.txt"
MATCH='admin|dev|portal|stage|prod|tst|test'
SEVERITY='P5 - INFO'
GREP_OPTIONS='-i'
SEARCH='positive'
SECONDARY_COMMANDS=''
TYPE='network'