AUTHOR='@xer0dayz'
VULN_NAME='Subover Takeover Detected'
FILENAME="$LOOT_DIR/nmap/subover-$TARGET.txt"
MATCH="Takeover\ Possible"
SEVERITY='P2 - HIGH'
GREP_OPTIONS='-i'
SEARCH='positive'
SECONDARY_COMMANDS=''
TYPE="network"