name: publish
on:
  push:

jobs:
  publish-to_ghcr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the hello-docker Docker image
        run: |
          container_img = ghcr.io/deselikem/hello-docker-gcr-demo
          echo $container_img
          docker build . -f Dockerfile.base --tag ghcr.io/deselikem/hello-docker-gcr-demo:latest
          #docker run ghcr.io/deselikem/hello-docker-gcr-demo:latest
          #docker push ghcr.io/deselikem/hello-docker-gcr-demo:latest