name: publish
on:
  push:

jobs:
  publish-to-ghcr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the hello-docker Docker image
        run: |
          echo "Builing and push..."
          repo_name=${{ github.repository }}
          repo_name=${repo_name,,}
          docker build . -f Dockerfile.base --tag ghcr.io/${repo_name}:latest
          docker run ghcr.io/${repo_name}:latest
          docker push ghcr.io/${repo_name}:latest