name: build and push

on:
  push:
    branches:
      - main
      - gh-action

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build and Push Docker image to ghcr.io'
        env:
          REPO_NAME: '${{ github.event.repository.name }}'
        run: |
          docker build . -f Dockerfile.base --tag ghcr.io/${GITHUB_REPOSITORY,,}:latest
          docker push ghcr.io/${GITHUB_REPOSITORY,,}:latest
