name: build and push

on:
  push:
    branches:
      - main
      - gh-action

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: name1
        run: |
          echo "repolower=${${{ github.event.repository.name }},,}" >>${GITHUB_ENV}


      - name: 'Build Inventory Image'
        env:
          REPO_NAME: '${{ github.event.repository.name }}'
        run: |
          echo "repolower=${REPO_NAME,,}" >>${GITHUB_ENV}
          echo "$repolower"
          echo "${repolower}"

          # docker build . -f Dockerfile.base --tag ghcr.io/abnerrizzi/${REPO_NAME}:latest
          # docker push ghcr.io/abnerrizzi/${REPO_NAME}:latest
